package com.heavendeeds.heavendeeds.exception;

public enum HeavenApiExceptionCode {
    CREATE_USER_EXCEPTION, INVALID_INPUT_EXCEPTION, EMAIL_ALREADY_EXIST, INVALID_USER_ASSOCIATION, USER_NOT_FOUND_EXCEPTION,
    UPDATE_DETAILS_EXCEPTION, CLEAN_USER_EXCEPTION, GET_ALL_USER_EXCEPTION, INVALID_EMAIL_EXCEPTION, EMAIL_SEND_EXCEPTION, USER_ROLE_NOT_FOUND, AUTH_IS_NOT_ALLOWED_TO_UPDATE
    ,PROPERTY_EXCEPTION,PROPERTY_CREATE_EXCEPTION,GET_ALL_PROPERTY_EXCEPTION;
}
